### ISSUE TITLE
Version Without VorpX

### ISSUE THREAD

**Issue by elliotttate** [convexvr/sims4-vr#1]
Hey! This looks really interesting! I think I have some ideas how to build this without needing VorpX, still getting stereoscopic to be able to make a more open source and easily usable mod. If you're interested in chatting, we'd love you to join our Flatscreen 2 VR Modding Discord here https://discord.gg/RgSnyuZExb  Thanks!

**Comment by convexvr** [comment]
New version that does not use VorpX is now working.
