### ISSUE TITLE
Left eye projected onto both sides

### ISSUE THREAD

**Issue by Dalokron** [convexvr/sims4-vr#10]
The mod was working the first couple times I loaded it (albeit with lag back and forth) but it was at least "working as was intended"), now only the left eye is ever shown, and thus it just looks 2D all over again... I've even deleted and reinstalled the mod, I cannot get the back and forth switching to even work anymore. The mod is definitely active and running, since I can press B on my Quest 2 controller and it warps correctly, but only the left eye's image is being projected

**Comment by convexvr** [comment]
Thanks for your effort.
