### ISSUE TITLE
Exceptions and compatibility 

### ISSUE THREAD

**Issue by YoananaoY** [convexvr/sims4-vr#12]
Game seems slower after installing mod, a lot of Exceptions, not compatibile with life and death pack

**Comment by YoananaoY** [comment]
[BE-ExceptionReport-20241117-191719.zip](https://github.com/user-attachments/files/17791855/BE-ExceptionReport-20241117-191719.zip)

**Comment by convexvr** [comment]
Read the readme.
The mod is no longer functional.
Please make a fork of the repo if you want to fix it.
