### ISSUE TITLE
Mod doesn't start

### ISSUE THREAD

**Issue by HayabusaCB** [convexvr/sims4-vr#2]
Hey, so the mod somehow doesn't start. Could that be because I use the EA App version (formerly Origin)? I installed it into the mods folder in the documents Sims 4 folder and when I connect my Quest 2 via Riftlink and press B, nothing happens ingame. Only in the Oculus App. Starting SteamVR itself also doesn't help. Any solutions?

**Comment by convexvr** [comment]
I have tested with EA App and it does not seam effect the mod. So that should be fine.
Steam VR should open automatically as you start sims 4 when the mod is working.

Have you enabled mods in the sims 4?

Copy the debug log, and paste it here.

This is where the debug log file is located:
C:\Users\$USER\Documents\Electronic Arts\The Sims 4\Mods\convexvr_sims4-vr\debug_log.txt

**Comment by HayabusaCB** [comment]
> I have tested with EA App and it does not seam effect the mod. So that should be fine. Steam VR should open automatically as you start sims 4 when the mod is working.
> 
> Have you enabled mods in the sims 4?
> 
> Copy the debug log, and paste it here.
> 
> This is where the debug log file is located: C:\Users$USER\Documents\Electronic Arts\The Sims 4\Mods\convexvr_sims4-vr\debug_log.txt

Yeah I have mods enabled, also Script mods but nothing works. I even uninstalled the game and started with a fresh version but still nothing. I thought maybe It's cuz I got the german version and so I uninstalled and installed the english one but still... anyway the log is:

2023-02-26 16:34:33: module loading initiated
2023-02-26 16:34:33: Reading memmory
2023-02-26 16:34:33: Done reading memmory
2023-02-26 16:34:33: Scale_patch_address1: 0x14107b578 Scale_patch_address2: 0x14107b565 code_injection_base_address: 0x14022b4fe
2023-02-26 16:34:33: patchlocation: 0(0x14107b578) = 0f119180000000410f28d20f14d7f30f59f4410f28e3f30f59c5f3410f5ee10f
2023-02-26 16:34:33: patchlocation: 1(0x14107b565) = 0f1151700f57d20f14c80f28c40f14d10f57c90f119180000000410f28d20f14
2023-02-26 16:34:33: patchlocation: 2(0x14022b4fe) = 0f1141300f104a400f1149400f1042500f1141500f104a600f1149600f104270
2023-02-26 16:51:52: module loading initiated
2023-02-26 16:51:52: Reading memmory
2023-02-26 16:51:52: Done reading memmory
2023-02-26 16:51:52: Scale_patch_address1: 0x14107b578 Scale_patch_address2: 0x14107b565 code_injection_base_address: 0x14022b4fe
2023-02-26 16:51:52: patchlocation: 0(0x14107b578) = 0f119180000000410f28d20f14d7f30f59f4410f28e3f30f59c5f3410f5ee10f
2023-02-26 16:51:52: patchlocation: 1(0x14107b565) = 0f1151700f57d20f14c80f28c40f14d10f57c90f119180000000410f28d20f14
2023-02-26 16:51:52: patchlocation: 2(0x14022b4fe) = 0f1141300f104a400f1149400f1042500f1141500f104a600f1149600f104270

**Comment by HayabusaCB** [comment]
I am also 100% running the 64-bit version so I am completely at a loss on what could cause this issue.

**Comment by convexvr** [comment]
Those logs has given me a suspicion of what it might be.
I made a new release that has some extra logging that will show if my suspicion is correct.
Download and install the latest https://github.com/convexvr/sims4-vr/releases/download/release/convexvr_sims4-vr-bundle.zip
Then try launching sims4 again and post the resulting debug log.

**Comment by HayabusaCB** [comment]
I downloaded the new version but it doesn't seem to show more log entries but here it is:


2023-02-27 21:19:03: module loading initiated
2023-02-27 21:19:03: Reading memmory
2023-02-27 21:19:03: Done reading memmory
2023-02-27 21:19:03: Scale_patch_address1: 0x14107b578 Scale_patch_address2: 0x14107b565 code_injection_base_address: 0x14022b4fe
2023-02-27 21:19:03: patchlocation: 0(0x14107b578) = 0f119180000000410f28d20f14d7f30f59f4410f28e3f30f59c5f3410f5ee10f
2023-02-27 21:19:03: patchlocation: 1(0x14107b565) = 0f1151700f57d20f14c80f28c40f14d10f57c90f119180000000410f28d20f14
2023-02-27 21:19:03: patchlocation: 2(0x14022b4fe) = 0f1141300f104a400f1149400f1042500f1141500f104a600f1149600f104270
2023-02-27 21:19:03: loading openvr_api
2023-02-27 21:19:03: loading vrdll

**Comment by convexvr** [comment]
Actually you have two more entries:
```
2023-02-27 21:19:03: loading openvr_api
2023-02-27 21:19:03: loading vrdll
```
Those logs where useful, there is a .dll file that is not loading.
I made a new version, that will tell us why the .dll file is not loading.
https://github.com/convexvr/sims4-vr/releases/download/release/convexvr_sims4-vr-bundle.zip
Download that and post the logs again.

**Comment by SimsGuy** [comment]
@convexvr 

Log:

```
2023-02-28 00:09:42: module loading initiated
2023-02-28 00:09:42: Reading memmory
2023-02-28 00:09:43: Done reading memmory
2023-02-28 00:09:43: Scale_patch_address1: 0x14107b578 Scale_patch_address2: 0x14107b565 code_injection_base_address: 0x14022b4fe
2023-02-28 00:09:43: patchlocation: 0(0x14107b578) = 0f119180000000410f28d20f14d7f30f59f4410f28e3f30f59c5f3410f5ee10f
2023-02-28 00:09:43: patchlocation: 1(0x14107b565) = 0f1151700f57d20f14c80f28c40f14d10f57c90f119180000000410f28d20f14
2023-02-28 00:09:43: patchlocation: 2(0x14022b4fe) = 0f1141300f104a400f1149400f1042500f1141500f104a600f1149600f104270
2023-02-28 00:09:43: loading openvr_api
2023-02-28 00:09:43: loading vrdll: C:\Users\USERNAME\Documents\Electronic Arts\The Sims 4\Mods\s4vrlib.dll
2023-02-28 00:09:43: could not load vrdll: [WinError 126] The specified module could not be found
2023-02-28 00:09:47: module loading initiated
2023-02-28 00:09:47: Reading memmory
2023-02-28 00:09:47: Done reading memmory
2023-02-28 00:09:47: Scale_patch_address1: 0x14107b578 Scale_patch_address2: 0x14107b565 code_injection_base_address: 0x14022b4fe
2023-02-28 00:09:47: patchlocation: 0(0x14107b578) = 0f119180000000410f28d20f14d7f30f59f4410f28e3f30f59c5f3410f5ee10f
2023-02-28 00:09:47: patchlocation: 1(0x14107b565) = 0f1151700f57d20f14c80f28c40f14d10f57c90f119180000000410f28d20f14
2023-02-28 00:09:47: patchlocation: 2(0x14022b4fe) = 0f1141300f104a400f1149400f1042500f1141500f104a600f1149600f104270
2023-02-28 00:09:47: loading openvr_api
2023-02-28 00:09:47: loading vrdll: C:\Users\USERNAME\Documents\Electronic Arts\The Sims 4\Mods\s4vrlib.dll
2023-02-28 00:09:47: could not load vrdll: [WinError 126] The specified module could not be found
```

The appropriate .dlls are in the folder, but, it refuses to load.

My mods are enabled and all other mods work. It appear to have trouble loading the updated version of vrdll.

**Comment by convexvr** [comment]
Could be that you need to install.
"Install Microsoft Visual C++ Redistributable"
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

https://aka.ms/vs/17/release/vc_redist.x64.exe

You also need directx9 directx 10, directx11 & directx 12. But i think those things should be installed with windows these days. 

Tell me if installing vc_redist did the job.

For my own reference:....
```
dumpbin /EXPORTS /IMPORTS /DEPENDENTS "convexvr_sims4-vr\s4vrlib.dll"

  Image has the following dependencies:

    d3d9.dll
    d3dx9d_43.dll
    openvr_api.dll
    KERNEL32.dll
    USER32.dll
    d3d11.dll
    dxgi.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll

  Section contains the following exports for vrdll.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
          12 number of functions
          12 number of names

    ordinal hint RVA      name

          1    0 00001A90 get_button_value = get_button_value
          2    1 00001AB0 get_float_value = get_float_value
          3    2 00003A40 init = init
          4    3 00001D10 set_added_rotation = set_added_rotation
          5    4 00001BF0 set_follow = set_follow
          6    5 00001C00 set_offset = set_offset
          7    6 00001C60 set_origin = set_origin
          8    7 00001CE0 set_position_scale = set_position_scale
          9    8 00001D40 set_scale = set_scale
         10    9 00001D80 set_struct_location = set_struct_location
         11    A 00001CC0 set_vr_active = set_vr_active
         12    B 000025F0 update = update

  Section contains the following imports:

    d3d9.dll
             18000E398 Import Address Table
             180012118 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                           A Direct3DCreate9Ex

    d3dx9d_43.dll
             18000E3A8 Import Address Table
             180012128 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          B7 D3DXLoadSurfaceFromSurface

    openvr_api.dll
             18000E3C8 Import Address Table
             180012148 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                           6 VR_GetInitToken
                          11 VR_ShutdownInternal
                           C VR_InitInternal2
                           5 VR_GetGenericInterface
                           E VR_IsInterfaceVersionValid

    KERNEL32.dll
             18000E000 Import Address Table
             180011D80 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                         104 CreateToolhelp32Snapshot
                         397 IsDebuggerPresent
                         47B RaiseException
                         408 MultiByteToWideChar
                         629 WideCharToMultiByte
                         4E9 RtlCaptureContext
                         4F1 RtlLookupFunctionEntry
                         1BD FreeLibrary
                         2CB GetProcessHeap
                         28C GetModuleHandleW
                         430 OutputDebugStringW
                         37C InitializeCriticalSection
                         11B DeleteCriticalSection
                         141 EnterCriticalSection
                         3D6 LeaveCriticalSection
                          8E CloseHandle
                          F5 CreateSemaphoreW
                         274 GetLastError
                         382 InitializeSRWLock
                           0 AcquireSRWLockExclusive
                         4CC ReleaseSRWLockExclusive
                           1 AcquireSRWLockShared
                         4CE ReleaseSemaphore
                         4CD ReleaseSRWLockShared
                         602 WaitForSingleObject
                         42F OutputDebugStringA
                         2C4 GetProcAddress
                         1B2 FlushInstructionCache
                         5F7 VirtualProtect
                         365 HeapCreate
                         366 HeapDestroy
                         363 HeapAlloc
                         36A HeapReAlloc
                         367 HeapFree
                         22A GetCurrentProcess
                         22B GetCurrentProcessId
                         22F GetCurrentThreadId
                         42B OpenThread
                         311 GetThreadContext
                         57C SetThreadContext
                         5AF SuspendThread
                         4E7 ResumeThread
                         5A7 Sleep
                         5B6 TerminateProcess
                         5C6 Thread32First
                         5C7 Thread32Next
                         5F1 VirtualAlloc
                         5F4 VirtualFree
                         5F9 VirtualQuery
                         2FB GetSystemInfo
                         597 SetUnhandledExceptionFilter
                         5D8 UnhandledExceptionFilter
                         4F8 RtlVirtualUnwind
                         39E IsProcessorFeaturePresent
                         464 QueryPerformanceCounter
                         301 GetSystemTimeAsFileTime
                         381 InitializeSListHead

    USER32.dll
             18000E1D0 Import Address Table
             180011F50 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          B5 DestroyWindow
                          76 CreateWindowExW
                         2DE RegisterClassExW
                         283 MessageBoxA
                          A7 DefWindowProcW

    d3d11.dll
             18000E388 Import Address Table
             180012108 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                           4 D3D11CreateDevice

    dxgi.dll
             18000E3B8 Import Address Table
             180012138 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                           1 CreateDXGIFactory1

    VCRUNTIME140_1.dll
             18000E268 Import Address Table
             180011FE8 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                           0 __CxxFrameHandler4

    VCRUNTIME140.dll
             18000E200 Import Address Table
             180011F80 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          21 __std_exception_copy
                          22 __std_exception_destroy
                          3C memcpy
                          3E memset
                           8 __C_specific_handler
                           9 __C_specific_handler_noexcept
                           1 _CxxThrowException
                          25 __std_type_info_destroy_list
                          2E __vcrt_GetModuleFileNameW
                          31 __vcrt_LoadLibraryExW
                          23 __std_terminate
                          36 _purecall

    api-ms-win-crt-time-l1-1-0.dll
             18000E370 Import Address Table
             1800120F0 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          24 _localtime64_s
                          30 _time64

    api-ms-win-crt-heap-l1-1-0.dll
             18000E278 Import Address Table
             180011FF8 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          19 malloc
                           8 _callnewh
                          18 free

    api-ms-win-crt-stdio-l1-1-0.dll
             18000E330 Import Address Table
             1800120B0 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          80 fputs
                           B __stdio_common_vsnprintf_s
                          7E fopen_s
                          74 fclose

    api-ms-win-crt-math-l1-1-0.dll
             18000E298 Import Address Table
             180012018 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          4F asin
                         116 sqrt
                          8E copysignf
                          91 cosf
                         113 sinf
                          C3 fmax
                          54 atan
                          55 atan2

    api-ms-win-crt-runtime-l1-1-0.dll
             18000E2E0 Import Address Table
             180012060 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          3F _seh_filter_dll
                          18 _configure_narrow_argv
                          33 _initialize_narrow_environment
                          34 _initialize_onexit_table
                          22 _execute_onexit_table
                          16 _cexit
                          36 _initterm
                          37 _initterm_e
                          39 _invalid_parameter_noinfo_noreturn

    api-ms-win-crt-string-l1-1-0.dll
             18000E358 Import Address Table
             1800120D8 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          85 strcat_s
                          89 strcpy_s

```

**Comment by SimsGuy** [comment]
@convexvr 

I installed "Microsoft Visual C++ Redistributable" again and made sure I had DirectX installed. (Reinstalled DirectX runtime to make sure). Restarted after each install.

Same error. 

The VorpX version of the mod seems to work (I at-least get to Steam theatre "Connecting to Game"), but the SteamVR version results in the error I shared with Steam theatre instantly closing.

**Comment by convexvr** [comment]
I think i found the issue, the mod was linked to d3dx9d_43.dll a debug verison of directx9 instead of d3dx9_43.dll

Try new version:
https://github.com/convexvr/sims4-vr/releases/download/release/convexvr_sims4-vr-bundle.zip

This said, if you had the vorpx version of the mod, sticking with that might not be a bad idea.
The new version has some benefits like, 1:1 perfect mapping of camera perspective, but to get stereo view the new version uses a cruder system witch halfs the framerate.
And the controls for the new version is slightly worse.

These things could be fixed. But i wont do it unless someone pays me to do it, it is to much work.

**Comment by SimsGuy** [comment]
That appears to have fixed it. Thank you, :D

**Comment by HayabusaCB** [comment]
> Actually you have two more entries:
> 
> ```
> 2023-02-27 21:19:03: loading openvr_api
> 2023-02-27 21:19:03: loading vrdll
> ```
> 
> Those logs where useful, there is a .dll file that is not loading. I made a new version, that will tell us why the .dll file is not loading. https://github.com/convexvr/sims4-vr/releases/download/release/convexvr_sims4-vr-bundle.zip Download that and post the logs again.

So here's the new log:
2023-02-28 22:33:57: module loading initiated
2023-02-28 22:33:57: Reading memmory
2023-02-28 22:33:57: Done reading memmory
2023-02-28 22:33:57: Scale_patch_address1: 0x14107b578 Scale_patch_address2: 0x14107b565 code_injection_base_address: 0x14022b4fe
2023-02-28 22:33:57: patchlocation: 0(0x14107b578) = 0f119180000000410f28d20f14d7f30f59f4410f28e3f30f59c5f3410f5ee10f
2023-02-28 22:33:57: patchlocation: 1(0x14107b565) = 0f1151700f57d20f14c80f28c40f14d10f57c90f119180000000410f28d20f14
2023-02-28 22:33:57: patchlocation: 2(0x14022b4fe) = 0f1141300f104a400f1149400f1042500f1141500f104a600f1149600f104270
2023-02-28 22:33:57: loading openvr_api
2023-02-28 22:33:58: loading vrdll: C:\Users\Connor\Documents\Electronic Arts\The Sims 4\Mods\convexvr_sims4-vr\s4vrlib.dll
2023-02-28 22:33:59: could not load vrdll: [WinError 126] Das angegebene Modul wurde nicht gefunden

the last sentence is german and means "the specified module couldn't be found"

I'll download your newest version to see if that generally fixes it, maybe that fixes it for me too

**Comment by HayabusaCB** [comment]
Okay so I tried it and here's the new Log, I'll just translate the german stuff immediatly:

2023-02-28 22:40:37: module loading initiated
2023-02-28 22:40:37: Reading memmory
2023-02-28 22:40:37: Done reading memmory
2023-02-28 22:40:37: Scale_patch_address1: 0x14107b578 Scale_patch_address2: 0x14107b565 code_injection_base_address: 0x14022b4fe
2023-02-28 22:40:37: patchlocation: 0(0x14107b578) = 0f119180000000410f28d20f14d7f30f59f4410f28e3f30f59c5f3410f5ee10f
2023-02-28 22:40:37: patchlocation: 1(0x14107b565) = 0f1151700f57d20f14c80f28c40f14d10f57c90f119180000000410f28d20f14
2023-02-28 22:40:37: patchlocation: 2(0x14022b4fe) = 0f1141300f104a400f1149400f1042500f1141500f104a600f1149600f104270
2023-02-28 22:40:37: loading openvr_api
2023-02-28 22:40:37: loading vrdll: C:\Users\Connor\Documents\Electronic Arts\The Sims 4\Mods\convexvr_sims4-vr\s4vrlib.dll
2023-02-28 22:40:37: initiating vrdll
2023-02-28 22:40:37: initiation done
2023-02-28 22:40:37: patching sims4 binary in memory
2023-02-28 22:40:37: creating patch function
2023-02-28 22:40:37: jmp 0xacf0000
2023-02-28 22:40:37: injecting patch function jump
2023-02-28 22:40:37: injectied
2023-02-28 22:40:37: patching sims4 done
2023-02-28 22:40:37: Initiate Debug TCP connection
2023-02-28 22:40:39: Failed to connect to debug connection: [WinError 10061] No connection was possible, due to the target computer denying the connection
2023-02-28 22:40:39: Loaded VR Mod

It still just opened the game and not SteamVR.

But for now another thing that I wanna say is thank you for reaching out to us and helping us resolve that problem! You're a real one!

**Comment by convexvr** [comment]
> It still just opened the game and not SteamVR.

If you manually create a folder s4 in C:\
that is a folder at location c:\s4

Then start sims 4 the mod will fill that with 2 other log files.
Paste those logs here.

**Comment by HayabusaCB** [comment]
> > It still just opened the game and not SteamVR.
> 
> If you manually create a folder s4 in C: that is a folder at location c:\s4
> 
> Then start sims 4 the mod will fill that with 2 other log files. Paste those logs here.

okay so  the first one from the n_debug is:

set_scale: 0.855259, 1.129848

and the output one is:

Loaded dll
init
Created SharingExDx9
Created SharingExDxDevice
Hooking directX functions
Enabeling directX hooking functions
Hooked
OpenVRDirectMode::OpenVRDirectMode()
OpenVRDirectMode::Init


the other log in the convexvr folder in the mods folder is the same.

**Comment by convexvr** [comment]
> It still just opened the game and not SteamVR.
> OpenVRDirectMode::OpenVRDirectMode()
> OpenVRDirectMode::Init
> the other log in the convexvr folder in the mods folder is the same.

Since it does not reach line https://github.com/convexvr/sims4-vr/blob/main/src/vrdll/vrdll/dllmain.cpp#L83
but it does reach https://github.com/convexvr/sims4-vr/blob/main/src/vrdll/vrdll/dllmain.cpp#L80
It should be working, the mod is detecting the headset so steamVR has to be up and running I cant see how it could not be.
I guess mabye we could see that type of output that you posted if the dll is crashing inside the function forwarder->Init(),

If you unplug your headset and start the game without it, what does the output log file say then?

**Comment by HayabusaCB** [comment]
Okay, here it is:
Loaded dll
init
Created SharingExDx9
Created SharingExDxDevice
Hooking directX functions
Enabeling directX hooking functions
Hooked
OpenVRDirectMode::OpenVRDirectMode()
OpenVRDirectMode::Init
vr init failed, no headset pressent



so it doesn't register my headset which means HMD recognition works BUT it has opened SteamVR! I'll try again in a second or later, cuz I'm getting ready for work rn lol

**Comment by HayabusaCB** [comment]
> > It still just opened the game and not SteamVR.
> > OpenVRDirectMode::OpenVRDirectMode()
> > OpenVRDirectMode::Init
> > the other log in the convexvr folder in the mods folder is the same.
> 
> Since it does not reach line https://github.com/convexvr/sims4-vr/blob/main/src/vrdll/vrdll/dllmain.cpp#L83 but it does reach https://github.com/convexvr/sims4-vr/blob/main/src/vrdll/vrdll/dllmain.cpp#L80 It should be working, the mod is detecting the headset so steamVR has to be up and running I cant see how it could not be. I guess mabye we could see that type of output that you posted if the dll is crashing inside the function forwarder->Init(),
> 
> If you unplug your headset and start the game without it, what does the output log file say then?

Okay, so it apparently fixed itself. It boots up SteamVR, then soon after it closes the application but it still works nonetheless!
