### ISSUE TITLE
Better Exceptions reports error in dll_test.py

### ISSUE THREAD

**Issue by Mordaur** [convexvr/sims4-vr#3]
as reported by Better Exceptions dll_test.py:46:

`The listed script mod failed to load and should be removed or updated. Failure: 'dll_test' (dll_test) 'bool' object has no attribute 'set_scale' (AttributeError: 'bool' object has no attribute 'set_scale')`

**Comment by convexvr** [comment]
I dont know what dll_test.py is.

I assume? "Better Exceptions" is this thing https://www.patreon.com/posts/better-v2-03-52688481

Seams like it is refering to this line:
https://github.com/convexvr/sims4-vr/blob/main/src/sims4-vr/src/main.py#L366
But it does not make sense.
If the code at this line fails:
https://github.com/convexvr/sims4-vr/blob/main/src/sims4-vr/src/main.py#L361
The mod should log an error to the log file and exit.

Dump the log file if you have issues:
C:\Users\$USER\Documents\Electronic Arts\The Sims 4\Mods\convexvr_sims4-vr\debug_log.txt
