### ISSUE TITLE
Not compatible with wmr

### ISSUE THREAD

**Issue by dzgreka** [convexvr/sims4-vr#5]
Headset: Lenovo Explorer
Headset displays zoomed in menu if mod was launched in main menu
If mod was launched in game, there is no picture at all

In both cases, cursor freaks out in the bottom corner of a screen and cant be controlled with mouse or motion controllers, mod also can't be turned off by pressing any buttons, the only way I found is pressing alt+ctrl+del.
I tried to play with steam bindings  "Pretend to be this type of controller" option with 0 success

**Comment by convexvr** [comment]
> Headset displays zoomed in menu if mod was launched in main menu

Yes that is what it does. I have been trying to improve this by using vr overlays but openvr keeps crashing when i add overlays, so it is staled work.

> If mod was launched in game, there is no picture at all

I don't know what this means. The mod is launched with the game.

> In both cases, cursor freaks out in the bottom corner of a screen

If the mouse is acting up. Then there must be some issue with the controls not mapping properly.

I can only test for the headset and controls that i have.

You are welcome to fix things and add support for other controllers. Just send a PR.
Or I am willing to spend some time and improve these things if you are willing to pay for my time.

**Comment by dzgreka** [comment]
What i meant is - after i load my save headset displays steamvr hub with "Sims4 loading", thats it
