### ISSUE TITLE
Mod does not work with Valve Index

### ISSUE THREAD

**Issue by subtlepaws** [convexvr/sims4-vr#7]
I have followed all of the instructions needed and no matter what I do, the game won't actually project into my headset. It stays on my monitor and doesn't mirror into the headset. I can see that it knows my headset is there as it moves the camera around with tracking the headset, I just can't see the game if I wear it.

**Comment by subtlepaws** [comment]
[debug_log.txt](https://github.com/convexvr/sims4-vr/files/13767327/debug_log.txt)

**Comment by xavikxavik** [comment]
I have the exact same problem/error in the Quest 3. I'm not sure if it's something about the headset or the connection.

**Comment by AtlasRedux** [comment]
> I have the exact same problem/error in the Quest 3. I'm not sure if it's something about the headset or the connection.

You're probably using the garbage Air Link or USB cable. Use Virtual Desktop. It connects fine then.
However, everything will still look wrong and warped, since you can't set custom resolutions in Sims 4. So the instructions makes no sense. Trying to set Quest 3 resolution will just make it default to HD at startup. So it's pointless.

**Comment by convexvr** [comment]
Warping should not have anything to do with resolution, see answer in #8
Don't know what you mean with setting the resolution of your headset.

Good to know that Virtual desktop is the thing to use. I have never used anything else.

**Comment by AtlasRedux** [comment]
> Warping should not have anything to do with resolution, see answer in #8 Don't know what you mean with setting the resolution of your headset.
> 
> Good to know that Virtual desktop is the thing to use. I have never used anything else.

Didn't mean setting resolution IN the headset, but setting the res. in Sims 4 to equal the per-eye res. of the headset. But since that shouldn't affect warping, just overset the res then. Can't set higher than 120Hz though, again a limitation of Sims 4 itself, so.
