### ISSUE TITLE
Everything warps as you move, wrong FoV, wrong scale, probably due to custom resolutions is not allowed in Sims 4

### ISSUE THREAD

**Issue by AtlasRedux** [convexvr/sims4-vr#8]
Quest 3.
You can't add custom resolutions in Sims 4.
If you try, it will just revert them when you start it.
View is warping as you move and scale is wrong.

**Comment by convexvr** [comment]
I updated the Readme with info on how you can force the resolution of the sims 4.

But i don't think the resolution of the headset or the game should have any effect on any kind of warping.
I know it did in the old vorpx version cause the vorpx api was very archaic. But now that the mod uses steamvr directly and the view projection matrix is copied straight from the headset in to the sims 4 resolution should not matter. (except when it comes to issues with clarity).

View direction and position is reported by steam vr on this line:
https://github.com/convexvr/sims4-vr/blob/0c918b16fa34d354a362fc9e3bf7a9f102e4d37f/src/vrdll/vrdll/python_exports.h#L648
Then it is combined with the eye position and the view projection and then send to the sims 4 in the function https://github.com/convexvr/sims4-vr/blob/0c918b16fa34d354a362fc9e3bf7a9f102e4d37f/src/vrdll/vrdll/python_exports.h#L386 

If you are seeing worping it is either cause steamvr is reporting bad projection matrixes or that some of the math that is combining the matrixes that steamvr is reporting is wrong in some subtle way. Or that sims4 has been updated.

**Comment by AtlasRedux** [comment]
You can't force the resolution. You can force the game from SAVING the resolution, but it will still just default to a standard resolution anyways, it just won't store it in the config file. But as said in the other thread, that apparently doesn't matter anyways, so just set a resolution that is higher than native, and whatever.
BUT, no idea which it is, but it is warping, like it has terrible FoV or the scene is partly spherical.

**Comment by convexvr** [comment]
It worked when i did it. Have you tried? (the menus will not say that the resolution has changed but it does.)

Mabye it is cause you are setting the resolution to high and steam VR is cropping instead of scaling?
